source 'http://rubygems.org'

gem 'rails', '3.2.0'
gem 'jquery-rails', '2.0.0'
# gem 'pg', '0.12.0'
# gem 'silent-postgres', '0.0.8'
gem 'thin', '1.3.1'
gem 'haml', '3.1.4'
# gem 'paperclip', '2.4.3'
# gem 'aws-s3', '0.6.2'
# gem 'paranoia', '1.1.0'
# gem 'omniauth', '1.0.1'
# gem 'omniauth-facebook', '1.1.0'

group :assets do
  gem 'sass-rails', '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'
  gem 'uglifier', '>= 1.0.3'
end

group :development, :test do
  gem 'fakeweb', '1.3.0'
  gem 'ruby-debug19', '0.11.6'
  gem 'heroku', '2.4.2'
  gem 'foreman', '0.20.0'
  gem 'integration', :git => 'git://github.com/mergulhao/integration.git'
  gem 'rspec-rails', '2.6.1'
  gem 'shoulda-matchers', '1.0.0'
  gem 'factory_girl_rails', '1.1.0'
  gem 'magic_encoding', '0.0.2'
  gem 'turn', '0.8.2', :require => false
  gem 'simplecov', '0.5.3', :require => false
  gem 'timecop', '0.3.5'
  gem 'valid_attribute', '1.2.0'
  gem 'tinder', '1.8.0'
end
